<?php
declare(strict_types=1);

require_once __DIR__ . '/../bootstrap.php';
require_once __DIR__ . '/../auth/middleware.php';

/**
 * Exactly two ways to be authorised for a receipt:
 *
 *   ?token=<64 hex>  the capability link issued to a guest donor by email.
 *                    No session — the token IS the authorisation.
 *   ?id=<bill id>    a signed-in member fetching their own receipt.
 *
 * Anything else is a 404. Previously a signed-out visitor fell through both
 * checks and got whatever bill id they asked for, and bill ids run in
 * sequence, so the entire receipts table could be walked by a stranger.
 *
 * 404 (not 403) on both failure modes on purpose: 403 would confirm that a
 * given bill id exists, which is exactly the signal an enumerator wants.
 */
$token = trim((string) ($_GET['token'] ?? ''));

if ($token !== '') {
    $receipt = ReceiptService::findByAccessToken($token);
} else {
    require_auth();
    $billId = trim((string) ($_GET['id'] ?? ''));
    $receipt = $billId === '' ? null : ReceiptService::findByBillId($billId, (int) Auth::id());
}

if (!$receipt) {
    Response::abort(404);
}

// Build the filename from the stored row, never from user input — $_GET could
// otherwise steer the Content-Disposition header.
$filename = preg_replace('/[^A-Za-z0-9._-]/', '', (string) $receipt['bill_id']) ?: 'receipt';

/**
 * The button says "Download PDF", so this sends a PDF. It used to send a
 * plain-text file, which is not a document a donor can keep or submit.
 *
 * Layout mirrors the on-screen receipt in pages/userhome.php so the printed
 * copy and the downloaded copy are recognisably the same document.
 */
$ink     = [15, 23, 42];    // headings
$muted   = [100, 116, 139]; // labels
$rule    = [203, 213, 225];
$brand   = [37, 99, 235];
$left    = 56.0;
$right   = Pdf::WIDTH - 56.0;
$width   = $right - $left;

$pdf = new Pdf();

// Header band
$pdf->rect(0, 0, Pdf::WIDTH, 96, [37, 99, 235]);
$pdf->text($left, 46, 'Sawa', 26, Pdf::BOLD, [255, 255, 255]);
$pdf->text($left, 68, 'Universal payment receipt', 10.5, Pdf::REGULAR, [219, 234, 254]);
$pdf->textRight($right, 46, 'RECEIPT', 13, Pdf::BOLD, [255, 255, 255]);
$pdf->textRight($right, 68, (string) $receipt['bill_id'], 10.5, Pdf::REGULAR, [219, 234, 254]);

$y = 140.0;

// Parties, side by side
$pdf->text($left, $y, 'ISSUED BY', 8, Pdf::BOLD, $muted);
$pdf->text($left + $width / 2, $y, 'PAID TO', 8, Pdf::BOLD, $muted);
$y += 16;
$pdf->text($left, $y, 'Sawa Together', 12, Pdf::BOLD, $ink);
$pdf->text($left + $width / 2, $y, (string) $receipt['recipient_label'], 12, Pdf::BOLD, $ink);
$y += 14;
$pdf->text($left, $y, 'Tripoli, Lebanon', 9.5, Pdf::REGULAR, $muted);
$pdf->text($left + $width / 2, $y, 'Verified campaign', 9.5, Pdf::REGULAR, $muted);

$y += 30;
$pdf->line($left, $y, $right, $y, 0.8, $rule);
$y += 26;

// Facts, two columns
$issued = new DateTimeImmutable((string) $receipt['created_at']);
$facts = [
    ['Bill ID', (string) $receipt['bill_id']],
    ['Date issued', $issued->format('F j, Y \a\t g:i A')],
    ['Status', 'Paid'],
    ['Payment method', (string) $receipt['method_label']],
    ['Provider reference', (string) ($receipt['provider_ref'] ?? 'Not applicable')],
    ['Currency', 'USD'],
];
foreach ($facts as $i => [$label, $value]) {
    $col = $i % 2;
    $x = $left + ($col * ($width / 2));
    $rowY = $y + (intdiv($i, 2) * 38);
    $pdf->text($x, $rowY, strtoupper($label), 8, Pdf::BOLD, $muted);
    $pdf->text($x, $rowY + 15, $value, 10.5, Pdf::REGULAR, $ink);
}
$y += (int) ceil(count($facts) / 2) * 38 + 10;

$pdf->line($left, $y, $right, $y, 0.8, $rule);
$y += 28;

// Money
$lines = [
    ['Donation', '$' . number_format((float) $receipt['subtotal'], 2)],
    ['Sawa support fee', '$' . number_format((float) $receipt['fee_amount'], 2)],
];
foreach ($lines as [$label, $value]) {
    $pdf->text($left, $y, $label, 11, Pdf::REGULAR, $ink);
    $pdf->textRight($right, $y, $value, 11, Pdf::REGULAR, $ink);
    $y += 24;
}

$y += 4;
$pdf->rect($left - 12, $y - 18, $width + 24, 40, [241, 245, 249]);
$pdf->text($left, $y + 6, 'Total paid', 12.5, Pdf::BOLD, $ink);
$pdf->textRight($right, $y + 6, '$' . number_format((float) $receipt['total_paid'], 2), 14, Pdf::BOLD, $brand);
$y += 56;

// Verification
$pdf->text($left, $y, 'RECEIPT CHECKSUM', 8, Pdf::BOLD, $muted);
$y += 14;
$y = $pdf->paragraph($left, $y, $width, (string) $receipt['checksum'], 8.5, 12, Pdf::REGULAR, $muted);
$y += 14;
$y = $pdf->paragraph(
    $left,
    $y,
    $width,
    'This receipt was generated by Sawa from its own payment records. The checksum above '
    . 'identifies this exact record and can be quoted when querying the payment.',
    9,
    13,
    Pdf::REGULAR,
    $muted
);

// Footer
$pdf->line($left, Pdf::HEIGHT - 72, $right, Pdf::HEIGHT - 72, 0.8, $rule);
$pdf->text($left, Pdf::HEIGHT - 54, 'Sawa - giving, together.', 9, Pdf::BOLD, $muted);
$pdf->textRight($right, Pdf::HEIGHT - 54, 'sawa.local', 9, Pdf::REGULAR, $muted);

$body = $pdf->output();

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $filename . '.pdf"');
header('Content-Length: ' . strlen($body));
// A receipt is per-user; proxies must not hold a copy.
header('Cache-Control: private, no-store');
echo $body;
exit;
